import styled from "styled-components"

export const MemberContainer = styled.div`
    width:100%;
    height:100%;
    background-color: rgb(238, 238, 238);
    .member{
        width:100%;
        height:100%;
        .header{
            width:7.5rem;
            height:1.68rem;
            margin:0 auto;
            background-image: linear-gradient(-135deg, #FF4C48 0%, #FF837E 100%);
        }
        .icon{
            height:0.88rem;
            width:100%;
            .icon_l{
                float:left;
                width:0.88rem;
                height:0.88rem;
                position:relative;
                i{
                    display:block;
                    width:0.44rem;
                    height:0.44rem;
                    position:absolute;
                    top:0;
                    bottom:0;
                    left:0;
                    right:0;
                    margin:auto;
                    text-align:center;
                    line-height:0.44rem;
                    font-size:0.42rem;
                    color:#fff;
                }
            }
            .icon_r{
                float:right;
                width:1.76rem;
                height:.88rem;
                div{
                    width:0.88rem;
                    height:0.88rem;
                    float:left;
                    position:relative;
                    i{
                        display:block;
                    width:0.44rem;
                    height:0.44rem;
                    position:absolute;
                    top:0;
                    bottom:0;
                    left:0;
                    right:0;
                    margin:auto;
                    text-align:center;
                    line-height:0.44rem;
                    font-size:0.42rem;
                    color:#fff;
                    }
                }
            }
        }
        .info{
            height:2.24rem;
            width:7.1rem;
            margin:0 auto;
            margin-top:-0.6rem;
            background:#fff;
            border-radius:0.05rem;
            padding-bottom:0.2rem;
            position:relative;
            padding-top:1.2rem;
            .info_up{
                position:absolute;
                height:1.08rem;
                width:100%;
                padding:0 0.1rem;
                top:-0.2rem;
                left:0;
                .info_up_l{
                    width:6.18rem;
                    height:100%;
                    float:left;
                    div{
                        float:left;
                    }
                    div:nth-child(1){
                        width:1.08rem;
                        height:1.08rem;
                        background-size:1.08rem 1.08rem;
                        background-repeat:no-repeat;
                        background-position:center;
                        img{
                            width:100%;
                            height:100%;
                        }
                    }
                    div:nth-child(2){
                        margin-left:0.2rem;
                        height:100%;
                        line-height:1.08rem;
                        color:#000;
                    }
                }
                .info_up_r{
                    position:absolute;
                    top:0.2rem;
                    right:0.2rem;
                    width:0.52rem;
                    height:0.72rem;   
                    img{
                        width:0.52rem;
                        height:0.52rem;
                        margin-top:0.2rem;
                    }
                }
            }
            .info_down{
                height:0.84rem;
                display:flex;
                justify-content:space-between;
                align-items:center;
                .info_down_box{
                    text-align:center;
                    height:100%;
                    width:33.33%;
                    div:nth-child(1){
                        height:0.34rem;
                        width:100%;
                    }
                    div:nth-child(2){
                        height:0.4rem;
                        width:100%;
                        margin-top:0.1rem;
                    }
                }
            }
        }
        .myorder{
            margin:auto;
            margin-top:0.2rem;
            width:7.1rem;
            height:2.26rem;
            background:#fff;
            .myorder_up{
                height:0.88rem;
                width:100%;
                padding:0.2rem;
                display:flex;
                justify-content:space-between;
                align-items:center;
                .myorder_up_l{
                    font-size:0.34rem;
                    font-weight: 700;
                }
                .myorder_up_r{
                    font-size:0.26rem;
                    color:#999;
                }
            }
            .myorder_down{
                height:1.38rem;
                display:flex;
                justify-content:space-between;
                align-items:center;
                .myorder_down_box{
                    width:20%;
                    height:100%;
                    text-align:center;
                    padding:0.2rem 0;
                    .myorder_down_box_pic{
                        width:100%;
                        height:0.44rem;
                        img{
                            width:0.44rem;
                            height:0.44rem;
                            margin:0 auto;
                        }
                    }
                    .myorder_down_box_text{
                        width:100%;
                        height:0.54rem;
                        text-align:center;
                        line-height:0.54rem;
                        font-size:0.26rem;
                        color:#666;
                    }
                }
            }
        }
    }

`